# Versão do docker-compose
version: '3.8'

# Definindo os serviços (nossos contêineres)
services:
  # Serviço 1: Servidor Web com PHP e Apache
  web:
    image: php:8.1-apache  # Usa uma imagem oficial do PHP 8.1 com Apache
    container_name: nexcommerce_web
    volumes:
      - ./src:/var/www/html/ # Mapeia a pasta 'src' do seu projeto para a pasta web do servidor
    ports:
      - "8080:80" # Acessa o site no seu navegador via http://localhost:8080
    depends_on:
      - db

  # Serviço 2: Servidor de Banco de Dados MySQL
  db:
    image: mysql:8.0 # Usa uma imagem oficial do MySQL 8.0
    container_name: nexcommerce_db
    restart: always
    environment:
      MYSQL_DATABASE: 'nexcommerce_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "33060:3306" # Acessa o banco de dados pela porta 33060
    volumes:
      - db_data:/var/lib/mysql

# Define um volume para persistir os dados do banco de dados
volumes:
  db_data: